version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    
### 새로 추가한 부분 ###
hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/health_check.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 300
      runas: ubuntu
