cloud:
  aws:
    credentials:
      accessKey: ${Image-access-key}
      secretKey: ${Image-secret-key}
    s3:
      bucket: s3-unanimous
    region:
      static: ap-northeast-2
    stack:
      auto: false


